require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

# iOS 14+ requerido por GoogleUserMessagingPlatform 2.x (UMP) con el plugin AdMob
platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/@capacitor/splash-screen'
  pod 'SquareetlabsCapacitorSubscriptions', :path => '../../node_modules/@squareetlabs/capacitor-subscriptions'
end

target 'App' do
  capacitor_pods
  # Fija UMP SDK 2.x para que el plugin AdMob siga usando UMPConsentStatus (3.x lo renombró)
  pod 'GoogleUserMessagingPlatform', '~> 2.6'
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
